const INSTALL_URL = "https://github.com/apps/python-templates-copier-update/installations/new";
const REPOSITORY_URL = "https://github.com/actions-ext/copier-update";
const SUPPORT_URL = `${REPOSITORY_URL}/issues/new/choose`;

export const styles = `
:root{color-scheme:dark;--bg:#070b16;--panel:#10182a;--panel-2:#151f35;--text:#f8f9ff;--muted:#aeb8ce;--cyan:#3bb3c4;--gold:#f8c301;--magenta:#b74f8e;--line:#2a3651}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0%,#17303c 0,transparent 30rem),var(--bg);color:var(--text);font:16px/1.6 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--cyan)}.shell{width:min(1120px,calc(100% - 2rem));margin:auto}.site-header{display:flex;align-items:center;justify-content:space-between;padding:1.25rem 0}.brand{display:flex;align-items:center;gap:.75rem;color:var(--text);font-weight:750;text-decoration:none}.brand-mark{width:2.3rem;height:2.3rem}.nav{display:flex;gap:1.25rem}.nav a,.footer a{color:var(--muted);text-decoration:none}.nav a:hover,.footer a:hover{color:var(--text)}main{padding:4rem 0 5rem}.hero{max-width:850px;padding:3rem 0 4.5rem}.eyebrow{color:var(--gold);font-size:.78rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.hero h1{font-size:clamp(2.8rem,8vw,5.6rem);line-height:.96;letter-spacing:-.055em;margin:.75rem 0 1.5rem}.hero p{max-width:720px;color:var(--muted);font-size:1.2rem}.actions{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:2rem}.button,button{display:inline-block;border:1px solid var(--line);border-radius:.65rem;padding:.7rem 1.05rem;color:var(--text);font:inherit;font-weight:700;text-decoration:none;cursor:pointer}.button.primary,button{border-color:transparent;background:linear-gradient(135deg,var(--magenta),#805ad5)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.card,.content,section{border:1px solid var(--line);border-radius:1rem;background:linear-gradient(160deg,var(--panel-2),var(--panel));padding:1.4rem}.hero,.steps{border:0;background:none;padding-left:0;padding-right:0}.card h2{font-size:1.05rem;margin:.3rem 0}.card p{color:var(--muted);margin:.35rem 0}.steps{counter-reset:step;display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-top:4rem}.step{border-top:1px solid var(--line);padding-top:1.2rem;color:var(--muted)}.step:before{counter-increment:step;content:"0" counter(step);display:block;color:var(--gold);font-size:.8rem;font-weight:800;letter-spacing:.12em;margin-bottom:.6rem}.content{max-width:820px;margin:auto}.content h1{font-size:2.6rem;line-height:1.1}.content h2{margin-top:2rem}.content p,.content li{color:var(--muted)}.content strong{color:var(--text)}header.dashboard{display:flex;justify-content:space-between;align-items:center}label{display:block;margin:.5rem 0}select{padding:.4rem}details{margin:1rem 0}.muted{color:var(--muted)}.error{color:#ff8d85}.footer{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid var(--line);padding:1.5rem 0 2.5rem;color:var(--muted);font-size:.9rem}.footer-links{display:flex;gap:1rem}@media(max-width:760px){.nav{display:none}main{padding-top:1rem}.grid,.steps{grid-template-columns:1fr}.hero{padding-bottom:3rem}.footer{display:block}.footer-links{margin-top:.5rem}header.dashboard{align-items:flex-start;gap:1rem}}
`;

const mark = `<svg class="brand-mark" viewBox="0 0 64 64" aria-hidden="true"><path d="M8 53V10h36l10 10v33H8M44 10v10h10" fill="none" stroke="#3bb3c4" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M17 52V20h22l8 8v24M39 20v8h8" fill="none" stroke="#d83280" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M26 52V30h9l7 7v8M35 30v7h7" fill="none" stroke="#f8c301" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M34 40v13M34 46h11v7" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/><circle cx="34" cy="40" r="4" fill="#fff"/><circle cx="45" cy="53" r="4" fill="#fff"/></svg>`;

export function publicLayout(title: string, description: string, content: string, status = 200): Response {
  return new Response(
    `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="description" content="${description}"><title>${title}</title><style>${styles}</style></head><body><div class="shell"><header class="site-header"><a class="brand" href="/">${mark}<span>Copier Update</span></a><nav class="nav" aria-label="Main navigation"><a href="/support">Support</a><a href="/privacy">Privacy</a><a href="${REPOSITORY_URL}">Source</a></nav></header><main>${content}</main><footer class="footer"><span>Free and open source from <a href="https://actions.python-templates.dev">actions-ext</a></span><span class="footer-links"><a href="/support">Support</a><a href="/privacy">Privacy</a><a href="/healthz">Status</a></span></footer></div></body></html>`,
    {
      status,
      headers: {
        "Cache-Control": "public, max-age=300",
        "Content-Security-Policy":
          "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",
        "Content-Type": "text/html; charset=utf-8",
        "Referrer-Policy": "no-referrer",
        "X-Content-Type-Options": "nosniff",
      },
    },
  );
}

export function landingPage(): Response {
  return publicLayout(
    "Copier Update — Keep generated repositories current",
    "Copier Update opens pull requests that bring Copier-managed repositories forward from their upstream templates.",
    `<section class="hero"><div class="eyebrow">GitHub App for Copier</div><h1>Template updates, delivered as pull requests.</h1><p>Install once to receive weekly updates from each repository's configured Copier template. No repository workflow, personal access token, or repository secret required.</p><div class="actions"><a class="button primary" href="${INSTALL_URL}">Install Copier Update</a><a class="button" href="/login">Request an update</a><a class="button" href="${REPOSITORY_URL}#readme">View documentation</a></div></section><section class="grid" aria-label="Benefits"><article class="card"><div class="eyebrow">Native</div><h2>Uses Copier's update model</h2><p>Answers files identify the upstream template and preserve each repository's recorded choices.</p></article><article class="card"><div class="eyebrow">Reviewable</div><h2>Every change arrives as a pull request</h2><p>Review generated changes, CI results, and conflicts before deciding whether to merge.</p></article><article class="card"><div class="eyebrow">Central</div><h2>No per-repository workflow</h2><p>The installed GitHub App supplies narrow repository tokens only while each update runs.</p></article></section><section id="how-it-works" class="steps" aria-label="How Copier Update works"><div class="step">Install the App on Copier-managed repositories.</div><div class="step">A weekly schedule or owner request selects eligible repositories.</div><div class="step">Copier renders the configured upstream template and refreshes known lockfiles.</div><div class="step">A dedicated branch and pull request expose the update for review.</div></section>`,
  );
}

export function supportPage(): Response {
  return publicLayout(
    "Support — Copier Update",
    "Get technical support for the Copier Update GitHub App.",
    `<article class="content"><div class="eyebrow">Support</div><h1>Get help with Copier Update</h1><p>For installation, update, or account questions, <a class="button primary" href="${SUPPORT_URL}">open a support issue</a>.</p><h2>Include useful details</h2><ul><li>Repository and update pull request URL</li><li>Approximate update time or workflow run URL</li><li>Expected and observed behavior</li><li>Whether the update was scheduled or requested manually</li></ul><p>Do not include private keys, OAuth tokens, session cookies, repository secrets, or private source content. Public source and current behavior are available in the <a href="${REPOSITORY_URL}">Copier Update repository</a>.</p></article>`,
  );
}

export function privacyPage(): Response {
  return publicLayout(
    "Privacy policy — Copier Update",
    "Privacy policy for the Copier Update GitHub App.",
    `<article class="content"><div class="eyebrow">Effective August 4, 2026</div><h1>Privacy policy</h1><p>Copier Update processes GitHub data to update repositories from the Copier templates they configure and to let account owners request updates.</p><h2>Data processed</h2><p>The App may process GitHub account identity, organization membership, installation and repository identifiers, repository names and settings, branches, pull requests, and repository file contents. It reads a repository's Copier answers file, clones the repository, and fetches the upstream template recorded by that file. Manual requests use GitHub OAuth to identify the requester and confirm personal-account ownership or organization-owner status.</p><h2>Use and retention</h2><p>Repository contents are held in an ephemeral GitHub Actions workspace while Copier computes an update. Resulting branches and pull requests remain on GitHub under the repository owner's control. The control plane stores the OAuth access token only in an encrypted, secure, HttpOnly session cookie that expires within eight hours. Copier Update maintains no customer database.</p><p>GitHub Actions and Cloudflare may retain operational logs under the publisher's configured retention settings. Logs may include account and repository names, pull request URLs, update outcomes, and error messages.</p><h2>Third-party services</h2><ul><li><strong>GitHub</strong> hosts the App, OAuth flow, update jobs, repositories, branches, and pull requests under the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement</a>.</li><li><strong>Cloudflare</strong> hosts the owner control plane, terminates network connections, and may process security and operational logs under the <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy policy</a>.</li><li><strong>Configured template hosts</strong> receive normal Git requests when Copier fetches the upstream template selected by a repository. Their policies and retention practices are controlled by that host.</li></ul><h2>Sharing and sale</h2><p>Copier Update does not sell personal data, use advertising, run analytics, or use repository data for generative AI or model training. Data is shared only with the services needed to run an update and the template host configured by the repository owner.</p><h2>Control and deletion</h2><p>Repository owners control access through the GitHub App installation and their Copier answers files. Suspending or uninstalling the App stops new processing. Owners can delete update branches and pull requests through GitHub. No customer profile or application database exists to delete. For privacy questions, use the <a href="/support">support page</a>.</p><h2>Changes</h2><p>Material changes will be published on this page with a revised effective date.</p></article>`,
  );
}
